services:
  mariadb-contratos:
    image: mariadb:10.11
    container_name: mariadb-contratos
    environment:
      MARIADB_DATABASE: ms_contratos
      MARIADB_USER: contratos_user
      MARIADB_PASSWORD: contratos_pass
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - mariadb_contratos:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - aeraxial_network

  aeraxial-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aeraxial-back
    depends_on:
      mariadb-contratos:
        condition: service_healthy
    environment:
      QUARKUS_HTTP_PORT: 8082
      QUARKUS_DATASOURCE_DB_KIND: mariadb
      QUARKUS_DATASOURCE_USERNAME: contratos_user
      QUARKUS_DATASOURCE_PASSWORD: contratos_pass
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mariadb://mariadb-contratos:3306/ms_contratos
      QUARKUS_FLYWAY_MIGRATE_AT_START: "true"
      QUARKUS_FLYWAY_BASELINE_ON_MIGRATE: "true"
      QUARKUS_HIBERNATE_ORM_LOG_SQL: "false"
      QUARKUS_SMALLRYE_OPENAPI_PATH: /openapi
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: "true"
    ports:
      - "8082:8082"
    networks:
      - aeraxial_network

volumes:
  mariadb_contratos:

networks:
  aeraxial_network:
    external: true