services:
  mariadb-contratos:
    image: mariadb:10.11
    container_name: mariadb-contratos
    environment:
      MARIADB_DATABASE: ms_contratos
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - mariadb_contratos:/var/lib/mysql

volumes:
  mariadb_contratos: